Double input support
computational-metabolomics/mspurity-galaxy pull request #11
Opened 2019-03-04 09:05 UTC by jsaintvanne

@yguitton @lecorguille

here are my changes for msPurity Galaxy.
I'm actually remove all indentations modifications to have less possible changes (sorry for that).
I try to explain changes file by file in lines just after :

## mspurity Galaxy
On all these tools I tried to have the same plan as W4M tools. I can change it if you prefer and add it in a new commit after the PR.
#### lib.R
[Add a lib.R file](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-ac5b7043553decc9c5e0cdbd225c87beR1) containing some repeated functions
I made this kind of file to avoid too much repeated functions in R files
#### assess_purity_msms.R
[Add a log file output](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433R3) (not really necessary if you don't want it)
Modify [input of libraries](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433R11)
Have to modify [it](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433R13)
[Change names](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433R27) to be able to run [function](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-ac5b7043553decc9c5e0cdbd225c87beR87) describe in lib.R file
No need of [filepaths](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433L41). I retrieve it like [this](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-3778fbedd0c25f3936f576b601fb1433R111)
Other things are indentations
#### assess_purity_msms.xml
[Add](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-57afbc9b25e6ff7feb28c0136e3126fdR18) @commandRscript@ to run a R tool
[Change variable for inputs](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-57afbc9b25e6ff7feb28c0136e3126fdR24) as singlefile_galaxyPath and singlefile_sampleName
[Add hidding](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-57afbc9b25e6ff7feb28c0136e3126fdR67) advanced options
[Delete conditional](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-57afbc9b25e6ff7feb28c0136e3126fdR59) for input data
[Add a log txt](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-57afbc9b25e6ff7feb28c0136e3126fdR89) as output
#### create_msp.R
[Adapt for W4M](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-dab65d31adac71362863e75a6d336b8eR1)
#### create_msp.xml
[Change indentation](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-0df0419244c27ee203733f71d815c5b8R12)
#### frag4feature.R
[Adapt](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR3) for W4M (add log file, indentation, describe process...)
[Add the file matching file parameter 
](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR31)
[Modify name of galaxy path and mzML files](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR38) to fit with our functions getRawfilePathFromArguments and retrieveRawfileInTheWorkingDirectory.
[Not really need xset object](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aL93) keep xdata
[Add CSVfile verification](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR63)
[Automatisation of convert2rawrt](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR75)
[Suppress use_group parameter because I automated](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aL150) it in msPurity package
[Try to make an easier output](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-4ce34a91d3e60549086b15cc7a23455aR143) table for users at the end
#### frag4feature.xml
[Have to change version](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R1)
[Add @command_scriptR@](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R21)
[Add filematchingfile parameter](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R27)
[Try to move file load conditionnal](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R46) in @command_fileload@
[Add advanced hidding options](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R70) (can be modify with different options easily)
[Add @command_logexit@](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R48) to add a log txt file
[Add parameter filematchingfile](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R57)
[Add output log](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R81)
[Modify output sqlite only when it is asking by user](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-f87e9d22f7f69764d16485492cbd1b45R88)
#### macro.xml
[Add @command_log_exit@](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-37d28be69fcb442e58202e9ea19e40b1R16) to add an exit in a log file
[Add @command_R_script@](https://github.com/computational-metabolomics/mspurity-galaxy/compare/master...workflow4metabolomics:double_input_support?expand=1#diff-37d28be69fcb442e58202e9ea19e40b1R14) to run a R tool
 [...]

2019-03-04 13:09 UTC, lecorguille requested changes

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.R
> +print(opt)
@jsaintvanne Remove this line

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.R
> +
@jsaintvanne Reduce the number of "little changes"

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.R
> +    im <- read.table(opt$isotope_matrix, header = TRUE, sep='\t', stringsAsFactors = FALSE)
@jsaintvanne Undo

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.xml
> +            <validator type="empty_field"/>
This validator isn't need. You can set the param as require

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.xml
> -            <when value="library">
@jsaintvanne You need to ask to authors if you can drop the libraries. We did in W4M but I remember that they still use this feature

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.xml
> +        <!-- Choose if your input has MS and MSn datas in the same file or not -->
@jsaintvanne Where is the choice?

2019-03-04 13:09 UTC, lecorguille commented on tools/create_msp.R
> +source("/home/jsaintvanne/W4M/mspurity-galaxyTest/tools/lib.R")
@jsaintvanne Aye!

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.R
> +source("/home/jsaintvanne/W4M/mspurity-galaxyTest/tools/lib.R")
@jsaintvanne Aye!

2019-03-04 13:09 UTC, lecorguille commented on tools/assess_purity_msms.xml
> +/!\\ WORK IN PROGRESS /!\\
@jsaintvanne Please remove this

2019-03-04 13:09 UTC, lecorguille commented on tools/frag4feature.R
> +source("/home/jsaintvanne/W4M/mspurity-galaxyTest/tools/lib.R")
@jsaintvanne The same

2019-03-04 13:09 UTC, lecorguille commented on tools/frag4feature.xml
> +<tool id="frag4feature" name="frag4feature" version="0.0.19">
@jsaintvanne Fix this: keep the original version numbers. The main author will decide at the time because at each rebase you will have conflit here.

2019-03-04 13:09 UTC, lecorguille commented on tools/lib.R
> +getMSFiles <- function (directory) {
@jsaintvanne I'm not sure you need this function?

2019-10-08 07:31 UTC, jsaintvanne commented
Can close it also @Tomnl I think :)

2019-10-08 07:31 UTC, closed without merging